// ═══════════════════════════════════════════════════════════════════════════════
// MANIFEST.JS - One Piece: Voyage of Dreams
// ═══════════════════════════════════════════════════════════════════════════════
// Auto-generated by create_game.py
// ═══════════════════════════════════════════════════════════════════════════════

export const manifest = {

  // ─────────────────────────────────────────────────────────────────────────────
  // GAME METADATA
  // ─────────────────────────────────────────────────────────────────────────────
  id: "one_piece",
  title: "One Piece: Voyage of Dreams",
  description: "A swashbuckling pirate adventure where the Straw Hat crew sails the treacherous Grand Line, battling fearsome enemies and chasing the ultimate treasure: the One Piece.",
  theme: "one_piece",
  startingScene: "intro",
  defeatScene: "epilogue_defeat",

  // ─────────────────────────────────────────────────────────────────────────────
  // UI THEME
  // ─────────────────────────────────────────────────────────────────────────────
  ui: {
    fonts: {
      primary: "'Crimson Text', Georgia, 'Times New Roman', serif",
      monospace: "'Courier New', Courier, monospace",
      heading: "'Cinzel', Georgia, 'Times New Roman', serif",
      sizes: {
        title: "17px",
        heading: "15px",
        body: "14px",
        small: "13px",
        tiny: "12px",
      },
      metrics: {
        lineHeight: 1.4,
        buttonPadding: 1.5,
        sectionGap: 2.0,
        charWidth: 0.55,
        descenderPadding: {
          small: { top: 2, bottom: 6 },
          medium: { top: 3, bottom: 8 },
          large: { top: 4, bottom: 10 },
        },
      },
    },
    colors: {
      dialogBg: 0x1a0a05,
      dialogBorder: 0xd4a843,
      panelBg: 0x0d0502,
      textPrimary: '#d4a843',
      textSecondary: '#c41e3a',
      textSpeaker: '#f4d03f',
      textDisabled: '#666666',
      buttonNormal: 0x2d2d44,
      buttonHover: 0x4a4a6a,
      buttonDisabled: 0x222233,
      buttonText: '#ffffff',
      healthOk: 0x4ade80,
      healthHurt: 0xfbbf24,
      healthCritical: 0xff6b6b,
      healthDown: 0xef4444,
      healthBarBg: 0x333333,
      initiative: {
        currentEnemy: 0x8b0000,
        currentParty: 0x2d5a27,
        inactive: 0x1a1a2e,
        enemyName: '#ff6666',
        partyName: '#88ff88',
        currentName: '#ffffff',
        indicator: '#ffff00',
      },
      enemy: {
        name: '#ff6b6b',
        placeholder: 0xcc0000,
      },
      party: {
        placeholder: 0x00cc00,
      },
      actionButton: {
        bg: 0x2d5a27,
        bgHover: 0x3d7a37,
        border: 0x4ade80,
        borderHover: 0x6bef6b,
      },
      infoButton: {
        bg: 0x3a3a5a,
        bgHover: 0x5a5a7a,
      },
      combat: {
        damageFlash: 0xff0000,
        damageText: '#ff4444',
        healText: '#44ff44',
        textStroke: '#000000',
      },
      dice: {
        critical: 0xffd700,
        success: 0x4ade80,
        partial: 0xfbbf24,
        failure: 0xef4444,
        boxBg: 0x333355,
        boxBorder: 0x666688,
        criticalTint: 0x4a6741,
        failureTint: 0x6b3030,
      },
      overlay: {
        dark: 0x000000,
        gradient1: 0x16213e,
        gradient2: 0x0f3460,
        victoryFlash: 0xffd700,
        defeatTint: 0x8b0000,
      },
      backButton: {
        bg: 0x2a2a3a,
        bgHover: 0x3a3a4a,
      },
    },
    dimensions: {
      healthBar: { width: 50, height: 10, borderRadius: 3 },
      enemyHealthBar: { width: 100, height: 12, borderRadius: 4, yOffset: 20 },
      portrait: { small: 20, medium: 22, large: 40 },
      initiative: { entryHeight: 30, panelWidth: 170, padding: 5 },
      ability: { buttonHeight: 52, buttonSpacing: 8, borderRadius: 6, namePaddingTop: 8, descPaddingTop: 28, rightColumnX: 45, sectionSpacing: 16 },
      dialogue: { padding: 20, speakerY: 15, textY: 45, indicatorSize: 14, borderRadius: 12 },
    },
    spacing: { healthBarRow: 28, portraitOffset: 15, nameOffset: 40 },
    animation: { damageFlash: 80, highlightPulse: 400, continuePulse: 600, healGlow: 150 },
    labels: {
      characterSelect: "Choose a Straw Hat:",
      unknownCharacter: "A mysterious pirate",
      abilitySelect: "Select Attack:",
      basicAttacksSection: "--- Basic Attacks ---",
      specialAbilitiesSection: "--- Special Techniques ---",
      initiativeHeader: "BATTLE ORDER",
      initiativeTitle: "BATTLE ORDER",
      roundTransition: "--- ROUND {round} ---",
      narrator: "Narrator",
      defeated: "DOWN!",
      hpLabel: "HP",
      continueIndicator: "▼",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // AI/NARRATOR CONFIGURATION
  // ─────────────────────────────────────────────────────────────────────────────
  ai: {
    projectId: "one_piece",
    partyTerms: {
      singular: "Pirate",
      plural: "Pirates",
      adjective: "Straw Hat",
      description: "a member of the party",
    },
    fallbackNarration: {
      breakFreeSuccess: "breaks free from the restraints",
      breakFreeFailure: "struggles against the restraints but remains trapped",
      unconscious: "is unconscious and cannot act",
      effects: {
        restrain: "The target is restrained!",
        poison: "Corruption deals {damage} additional damage!",
        slow: "The target is slowed!",
        mark: "The target is marked for bonus damage!",
        shield: "A protective barrier is raised!",
        concealment: "The party fades into concealment!",
        damage_reduction: "Defenses are weakened!",
        default: "{type} effect applied!",
      },
    },
    narratorPrompt: `You are the narrator for "One Piece: Voyage of Dreams", A swashbuckling pirate adventure where the Straw Hat crew sails the treacherous Grand Line, battling...

Your tone is:
- Epic and dramatic like a shonen anime narrator, building hype for big moments with dramatic pauses and emotional crescendos

Rules:
- Keep responses under 3 sentences unless asked for more
- Never break character or mention being an AI
- Make everything sound dramatic and entertaining
- Use short, punchy sentences`,
    narratorTone: {
      style: ["Epic and dramatic like a shonen anime narrator, building hype for big moments with dramatic pauses and emotional crescendos", "Balances intense action with comedic timing - one moment tearful backstory, next moment Luffy picking his nose during a serious conversation", "References willpower, dreams, and friendship constantly - these aren't just themes, they're literally power sources in this world"],
      rules: [
        "Keep responses to 2-3 sentences MAX",
        "Never break character or mention being an AI",
        "Make everything sound more epic than it probably is"
      ]
    },
    personalityStyles: {
      reckless: "impulsive, enthusiastic, charges in without thinking",
      paranoid: "suspicious, scheming, always has a backup plan",
      cheerful: "optimistic, accidentally competent, finds joy in chaos",
      sardonic: "sarcastic, weary, secretly caring",
    },
    narrationInstructions: {
      healParty: "channeling healing energy that flows to ALL party members!",
      buffParty: "CASTING protective magic over the ENTIRE party!",
      healSelf: "healing themselves with a burst of energy!",
    },
    npcPrompts: {}
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SCENE DISPLAY CONFIGURATION
  // ─────────────────────────────────────────────────────────────────────────────
  sceneDisplay: {
    victoryScenes: ["midboss_victory", "epilogue_victory"],
    dynamicCharacterDefaults: {
      x: 0.5,
      y: 0.45,
      maxSize: 180,
      successAnimation: { type: "bounce", duration: 600, ease: "Back.easeOut" },
      failureAnimation: { type: "shake", duration: 400, ease: "Power2" }
    },
    scenes: {
      midboss_victory: {
        party: { show: true, pose: "idle", y: 0.45, spacing: 0.2, startX: 0.15, maxSize: 140 }
      },
      epilogue_victory: {
        party: { show: true, pose: "idle", y: 0.45, spacing: 0.2, startX: 0.15, maxSize: 140 }
      }
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PARTY MEMBERS
  // ─────────────────────────────────────────────────────────────────────────────
  party: [
    {
      id: "monkey_d_luffy",
      name: "Monkey D. Luffy",
      images: {
        idle: "https://rosebud.ai/assets/monkey_d_luffy-idle.png?VCTK",
        attack: "https://rosebud.ai/assets/monkey_d_luffy-attack.png?oHgk",
        hurt: "https://rosebud.ai/assets/monkey_d_luffy-hurt.png?X95A",
        portrait: "https://rosebud.ai/assets/monkey_d_luffy-portrait.png?Ff3O",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Enforcer",
      stats: {
        brawn: 2,
        cunning: 0,
        spirit: 1,
      },
      maxHealth: 5,
      trait: "reckless",
      description: "A rubber-bodied captain with a straw hat and an endless appetite, who punches his way through every problem with stretchy fists and unshakeable determination",
      personality: "Luffy is simple-minded but incredibly perceptive about people's hearts. He makes decisions based on gut feeling, loves meat above all else, and will fight anyone who threatens his friends. He laughs in the face of danger because he genuinely finds it exciting.",
      song: "I'M GONNA BE KING OF THE PIRATES! Shishishi! Hey, is that meat? MEAT! Wait, we're fighting? GOMU GOMU NO... what was I doing again? Oh right, PUNCHING!",
    },    {
      id: "roronoa_zoro",
      name: "Roronoa Zoro",
      images: {
        idle: "https://rosebud.ai/assets/roronoa_zoro-idle.png?tKii",
        attack: "https://rosebud.ai/assets/roronoa_zoro-attack.png?8tij",
        hurt: "https://rosebud.ai/assets/roronoa_zoro-hurt.png?ppmZ",
        portrait: "https://rosebud.ai/assets/roronoa_zoro-portrait.png?VoPK",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Scout",
      stats: {
        brawn: 1,
        cunning: 1,
        spirit: 1,
      },
      maxHealth: 5,
      trait: "stubborn",
      description: "A green-haired swordsman who wields three swords simultaneously - one in each hand and one in his mouth - pursuing his dream to become the world's greatest swordsman",
      personality: "Zoro is stoic, loyal, and has absolutely no sense of direction. He gets lost going in a straight line. He naps constantly, drinks heavily, and trains obsessively. Despite his gruff exterior, he'd die for his captain without hesitation.",
      song: "Which way is north? ...Doesn't matter, I'll cut through. Three swords, one path, NOTHING can stop me! Now where did everyone go? They must have gotten lost. I'll just... go this way. *walks in opposite direction*",
    },    {
      id: "nami",
      name: "Nami",
      images: {
        idle: "https://rosebud.ai/assets/nami-idle.png?ATUg",
        attack: "https://rosebud.ai/assets/nami-attack.png?dlsv",
        hurt: "https://rosebud.ai/assets/nami-hurt.png?75Pe",
        portrait: "https://rosebud.ai/assets/nami-portrait.png?mbMe",
      },
      gender: "female",
      pronouns: { subject: "she", object: "her", possessive: "her" },
      class: "Hacker",
      stats: {
        brawn: 0,
        cunning: 2,
        spirit: 1,
      },
      maxHealth: 5,
      trait: "greedy",
      description: "A brilliant navigator and former thief with orange hair and a weather-controlling staff, whose love of treasure is only matched by her loyalty to her crew",
      personality: "Nami is clever, manipulative when needed, and absolutely obsessed with money and treasure. She's the voice of reason among chaos, though she's also prone to dramatic reactions. Deep down, she's fiercely protective of those she loves.",
      song: "That treasure is MINE! 100 million berries minimum or I'm not interested! ...Fine, I'll save you idiots, but you OWE me! With interest! Compounding daily!",
    },    {
      id: "tony_tony_chopper",
      name: "Tony Tony Chopper",
      images: {
        idle: "https://rosebud.ai/assets/tony_tony_chopper-idle.png?W6lM",
        attack: "https://rosebud.ai/assets/tony_tony_chopper-attack.png?Uymr",
        hurt: "https://rosebud.ai/assets/tony_tony_chopper-hurt.png?qqp7",
        portrait: "https://rosebud.ai/assets/tony_tony_chopper-portrait.png?6yaO",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Medic",
      stats: {
        brawn: 0,
        cunning: 1,
        spirit: 2,
      },
      maxHealth: 5,
      trait: "timid",
      description: "A tiny blue-nosed reindeer who ate the Human-Human Fruit, giving him human intelligence and the ability to transform between multiple forms, serving as the crew's doctor",
      personality: "Chopper is sweet, naive, and easily flustered by compliments (which he pretends to hate but clearly loves). He's terrified of scary things but will overcome his fear to protect his friends. His medical knowledge is exceptional despite his cute appearance.",
      song: "I-I'm not happy you called me cute, you jerk! *happy wiggly dance* I'm a MONSTER, not a tanuki! ...Do you need medical attention? I'LL SAVE YOU!",
    }
  ],

  // ─────────────────────────────────────────────────────────────────────────────
  // ABILITIES
  // ─────────────────────────────────────────────────────────────────────────────
  abilities: {
    monkey_d_luffy: {
      basicAttacks: [
        {
          id: "gomu_gomu_no_pistol",
          name: "Gomu Gomu no Pistol",
          description: "Stretches arm back and snaps it forward like a pistol shot!",
          stat: "brawn",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "gomu_gomu_no_gatling",
          name: "Gomu Gomu no Gatling",
          description: "Throws hundreds of punches so fast arms become invisible!",
          stat: "brawn",
          difficulty: "normal",
          damage: 3,
          uses: 2,
          targetType: "enemy",
        },        {
          id: "gomu_gomu_no_balloon",
          name: "Gomu Gomu no Balloon",
          description: "Inflates body like a balloon to bounce back attacks!",
          stat: "spirit",
          difficulty: "easy",
          effect: {
            type: "shield", reduction: 2, duration: 1, description: "Rubber body bounces attacks away harmlessly"
          },
          uses: 1,
          targetType: "self",
        }
      ],
    },    roronoa_zoro: {
      basicAttacks: [
        {
          id: "oni_giri",
          name: "Oni Giri",
          description: "Three-sword demon slash that cuts through anything!",
          stat: "brawn",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "santoryu_tatsumaki",
          name: "Santoryu: Tatsumaki",
          description: "Spins all three swords to create a dragon twister!",
          stat: "brawn",
          difficulty: "hard",
          damage: 4,
          uses: 2,
          targetType: "enemy",
        },        {
          id: "find_the_path",
          name: "Find the Path",
          description: "Somehow stumbles upon exactly what the crew needs... by getting lost.",
          stat: "cunning",
          difficulty: "normal",
          effect: {
            type: "reveal", duration: 1, description: "Accidentally discovered enemy weakness or hidden path"
          },
          uses: 1,
          targetType: "party",
        }
      ],
    },    nami: {
      basicAttacks: [
        {
          id: "clima_tact_strike",
          name: "Clima-Tact Strike",
          description: "Whacks enemies with her weather-controlling staff!",
          stat: "cunning",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "thunderbolt_tempo",
          name: "Thunderbolt Tempo",
          description: "Creates a localized thunderstorm to strike enemies with lightning!",
          stat: "cunning",
          difficulty: "normal",
          damage: 3,
          effect: {
            type: "stun", duration: 1, description: "Paralyzed by lightning strike"
          },
          uses: 2,
          targetType: "enemy",
        },        {
          id: "mirage_tempo",
          name: "Mirage Tempo",
          description: "Creates heat mirages to confuse enemies and help allies escape!",
          stat: "cunning",
          difficulty: "easy",
          effect: {
            type: "concealment", duration: 2, description: "Hidden by shimmering heat mirages"
          },
          uses: 1,
          targetType: "party",
        }
      ],
    },    tony_tony_chopper: {
      basicAttacks: [
        {
          id: "horn_point_attack",
          name: "Horn Point Attack",
          description: "Transforms to grow massive antlers and charges!",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "rumble_ball_heavy_point",
          name: "Heavy Point Smash",
          description: "Uses a Rumble Ball to transform into muscular human form and SMASH!",
          stat: "brawn",
          difficulty: "normal",
          damage: 3,
          uses: 2,
          targetType: "enemy",
        },        {
          id: "medical_expertise",
          name: "Medical Expertise",
          description: "Applies expert medical treatment to heal wounded crewmates!",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "heal", amount: 3
          },
          uses: 2,
          targetType: "party",
        }
      ],
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // ENEMIES
  // ─────────────────────────────────────────────────────────────────────────────
  enemies: {
    arlong: {
      id: "arlong",
      name: "Arlong",
      shortName: "Arlong",
      images: {
        idle: "https://rosebud.ai/assets/arlong-idle.png?uYbU",
        attack: "https://rosebud.ai/assets/arlong-attack.png?8zh4",
        hurt: "https://rosebud.ai/assets/arlong-hurt.png?D0cB",
        dead: "https://rosebud.ai/assets/arlong-dead.png?rJoX",
        portrait: "https://rosebud.ai/assets/arlong-portrait.png?QsBU",
        special: "https://rosebud.ai/assets/arlong-special.png?4vuQ",
      },
      creatureType: "Fishman",
      size: "Large",
      description: "A towering saw-shark fishman with razor teeth and a massive nose, leader of the Arlong Pirates who believes fishmen are the superior species destined to rule over humans",
      personality: "Arlong is cruel, arrogant, and harbors deep hatred for humans while hypocritically using them for his goals. He takes sadistic pleasure in human suffering and considers himself above all laws. His teeth regenerate endlessly, making his bite attacks relentless.",
      health: 12,
      stats: {
        cunning: 1,
      },
      attacks: [
        {
          id: "shark_on_darts",
          name: "Shark On Darts",
          description: "Launches through the air like a living missile, nose-first",
          damage: 2,
          damageType: "piercing",
          targeting: "highest_threat",
        },        {
          id: "tooth_gum",
          name: "Tooth Gum",
          description: "Rips out his own teeth to use as deadly weapons - they grow back instantly",
          damage: 1,
          damageType: "slashing",
          targeting: "random",
        },        {
          id: "shark_on_haguruma",
          name: "Shark On Haguruma",
          description: "Spins rapidly with arms extended, becoming a living saw blade",
          damage: 1,
          damageType: "slashing",
          targeting: "grouped",
        }
      ],
    },    crocodile: {
      id: "crocodile",
      name: "Sir Crocodile",
      shortName: "Crocodile",
      images: {
        idle: "https://rosebud.ai/assets/crocodile-idle.png?jki6",
        attack: "https://rosebud.ai/assets/crocodile-attack.png?ZdPu",
        hurt: "https://rosebud.ai/assets/crocodile-hurt.png?328l",
        dead: "https://rosebud.ai/assets/crocodile-dead.png?gAqp",
        portrait: "https://rosebud.ai/assets/crocodile-portrait.png?sFnN",
        attack2: "https://rosebud.ai/assets/crocodile-attack2.png?V9YO",
        special1: "https://rosebud.ai/assets/crocodile-special1.png?tzDo",
        special2: "https://rosebud.ai/assets/crocodile-special2.png?UXFg",
        transform: "https://rosebud.ai/assets/crocodile-transform.png?dqFg",
      },
      creatureType: "Human",
      size: "Large",
      description: "A tall, scarred man in a fur-lined coat with a golden hook for a left hand, wielding the Sand-Sand Fruit's power to become and control sand itself - one of the Seven Warlords of the Sea",
      personality: "Crocodile is calculating, patient, and utterly ruthless. He spent years building a criminal empire while masquerading as a hero. He views everyone as pawns and discards them without hesitation. His composure only breaks when his plans are truly threatened.",
      health: 18,
      stats: {
        cunning: 2,
      },
      attacks: [
        {
          id: "desert_spada",
          name: "Desert Spada",
          description: "Creates a blade of compressed sand that cuts through everything in its path",
          damage: 2,
          damageType: "slashing",
          targeting: "highest_threat",
        },        {
          id: "ground_secco",
          name: "Ground Secco",
          description: "Drains all moisture from anything touched, turning it to dust",
          damage: 1,
          damageType: "dehydration",
          targeting: "random",
        },        {
          id: "sables",
          name: "Sables",
          description: "Summons a massive sandstorm that engulfs all enemies",
          damage: 2,
          damageType: "bludgeoning",
          targeting: "grouped",
        }
      ],
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SCENES
  // ─────────────────────────────────────────────────────────────────────────────
  scenes: {
    intro: {
      id: "intro",
      title: "One Piece: Voyage of Dreams",
      type: "narrative",
      background: "https://rosebud.ai/assets/going_merry_deck.jpg?d3VR",
      music: "https://rosebud.ai/assets/death_and_honor.mp3?EzOG",
      openingText: `You are the STRAW HAT PIRATES! On the endless blue expanse of the Grand Line, where the impossible is Tuesday and dreams are the only compass worth following, you sail toward adventure. Your captain wants to be King of the Pirates. Your swordsman wants to be the world's greatest. Your navigator wants to chart every sea. Your doctor wants to cure any disease. Together, you are unstoppable... or at least entertainingly destructive.`,
      speaker: null,
      nextScene: "mission_briefing",
    },

    mission_briefing: {
      id: "mission_briefing",
      title: "The Mission",
      type: "narrative",
      background: "https://rosebud.ai/assets/east_blue_village.jpg?14k9",
      music: "https://rosebud.ai/assets/Abandoned_Island.mp3?qcw6",
      openingText: `Word reaches the crew of a tyrant who must be stopped. First, the fishman Arlong terrorizes the East Blue, extorting villages and crushing anyone who defies fishman supremacy. Then, the Warlord Crocodile plots to destroy an entire kingdom from the shadows. The crew sets sail - not for treasure this time, but because their friends need them. And Straw Hats always protect their friends.`,
      speaker: "The Glitch",
      choices: [
        {
          id: "accept_enthusiastically",
          label: "Accept enthusiastically!",
          character: "monkey_d_luffy",
          stat: "brawn",
          difficulty: "normal",
          outcomes: {
            success: {
              text: "Your enthusiasm is noted. The mission is on!",
              nextScene: "challenge_scene",
            },
            failure: {
              text: "Your enthusiasm is... excessive. But the mission continues.",
              nextScene: "challenge_scene",
            },
          },
        },
        {
          id: "plan_carefully",
          label: "Demand more details first",
          character: "roronoa_zoro",
          stat: "cunning",
          difficulty: "easy",
          outcomes: {
            success: {
              text: "Smart thinking. You gather additional intel before proceeding.",
              setFlag: "got_intel",
              nextScene: "challenge_scene",
            },
            failure: {
              text: "The broker doesn't appreciate the questions. Moving on...",
              nextScene: "challenge_scene",
            },
          },
        },
      ],
    },

    challenge_scene: {
      id: "challenge_scene",
      title: "The Checkpoint",
      type: "narrative",
      background: "https://rosebud.ai/assets/arlong_park.jpg?wLoP",
      music: "https://rosebud.ai/assets/Abandoned_Island.mp3?qcw6",
      openingText: `Before confronting the villains, the crew faces challenges that test their bonds. Luffy punches first and asks questions never. Zoro gets lost going to the bathroom. Nami calculates the cost of heroism (too high, but she'll do it anyway). Chopper hides behind things while peeking out (he's hiding wrong, but his heart's in the right place). Somehow, this disaster of a crew keeps winning.`,
      speaker: null,
      nextScene: "journey",
    },

    journey: {
      id: "journey",
      title: "The Journey",
      type: "narrative",
      background: "https://rosebud.ai/assets/arlong_battle.jpg?KxxV",
      music: "https://rosebud.ai/assets/Abandoned_Island.mp3?qcw6",
      openingText: `The journey across treacherous waters brings storms that would sink lesser ships, sea monsters that would terrify lesser crews, and meals that would bankrupt lesser cooks. Luffy nearly falls overboard reaching for a passing fish. Zoro trains through a hurricane. Nami screams at everyone to follow her navigation. Chopper treats injuries while somehow being the calmest person on deck. The Grand Line throws everything at them. They laugh and sail on.`,
      speaker: null,
      nextScene: "midboss_combat",
    },

    midboss_combat: {
      id: "midboss_combat",
      title: "Confrontation",
      type: "combat",
      background: "https://rosebud.ai/assets/arlong_victory.jpg?oUca",
      music: "https://rosebud.ai/assets/forward2.mp3?eYqv",
      combat: {
        version: 2,
        enemyId: "arlong",
        openingNarration: `Arlong looms over the battlefield, his shark teeth gleaming with malice. 'Inferior humans,' he sneers, 'you dare challenge the supreme fishmen?' Behind him, Arlong Park stands as a monument to his cruelty - built with the money Nami was forced to steal, year after year. But today, Luffy cracks his knuckles. Today, Nami's chains break. Today, Arlong learns why you never mess with Straw Hat Luffy's navigator.`,
        victoryScene: "midboss_victory",
        defeatScene: "epilogue_defeat",
      },
    },

    midboss_victory: {
      id: "midboss_victory",
      title: "Victory!",
      type: "narrative",
      background: "https://rosebud.ai/assets/grand_line_storm.jpg?GPE1",
      music: "https://rosebud.ai/assets/Somewhere.mp3?srwS",
      openingText: `Arlong Park crumbles as Luffy's final blow sends the fishman tyrant crashing through floor after floor. 'NAMI IS MY FRIEND!' Luffy roars, and the building that symbolized years of Nami's suffering collapses into rubble. The villagers of Cocoyama weep with joy. Nami, for the first time in eight years, smiles without hiding pain behind it. 'Luffy... help me.' He grins. 'Of course.'`,
      speaker: null,
      nextScene: "obstacle",
    },

    obstacle: {
      id: "obstacle",
      title: "The Void",
      type: "narrative",
      background: "https://rosebud.ai/assets/alabasta_desert.jpg?PSuQ",
      music: "https://rosebud.ai/assets/Abandoned_Island.mp3?qcw6",
      openingText: `The journey to Alabasta tests the crew's resolve. Desert heat threatens to cook them alive. Sandstorms erase their tracks. Crocodile's agents lurk everywhere, and the kingdom teeters on the edge of civil war. A princess fights alone to save her people. She shouldn't have to. The Straw Hats have come to help, whether the world likes it or not.`,
      speaker: null,
      nextScene: "explore_lair",
    },

    explore_lair: {
      id: "explore_lair",
      title: "The Lair",
      type: "narrative",
      background: "https://rosebud.ai/assets/rain_dinners.jpg?rHnf",
      music: "https://rosebud.ai/assets/Abandoned_Island.mp3?qcw6",
      openingText: `Rain Dinners casino glitters with false promise, but beneath it lurks Crocodile's true domain. The crew infiltrates through various means - Luffy through the front door (he doesn't understand 'subtle'), Zoro through a wall (he got lost), Nami through the VIP entrance (she charmed her way in), and Chopper disguised as a very unconvincing statue. The Bananawani circle in their pools below, waiting.`,
      speaker: null,
      nextScene: "finalboss_combat",
    },

    finalboss_combat: {
      id: "finalboss_combat",
      title: "Final Battle",
      type: "combat",
      background: "https://rosebud.ai/assets/crocodile_lair.jpg?Yzz9",
      music: "https://rosebud.ai/assets/Vengeance.mp3?ZJae",
      combat: {
        version: 2,
        enemyId: "crocodile",
        openingNarration: `Sir Crocodile sits on his throne, cigar smoke curling around his scarred face. 'You've come far, Straw Hat. But you cannot defeat sand itself.' He rises, his body already dissolving into golden grains. The Bananawani surface with hungry roars. This is a Warlord of the Sea - a pirate so powerful the World Government gave him legitimacy rather than fight him. Luffy grins. 'I've beat impossible before. I'll beat it again.'`,
        victoryScene: "epilogue_victory",
        defeatScene: "epilogue_defeat",
      },
    },

    epilogue_victory: {
      id: "epilogue_victory",
      title: "Victory!",
      type: "narrative",
      isEnding: true,
      background: "https://rosebud.ai/assets/victory.jpg?uDXf",
      music: "https://rosebud.ai/assets/Somewhere.mp3?srwS",
      openingText: `Crocodile falls. The rain that Alabasta has prayed for finally comes, washing away the lies and plots that nearly destroyed a kingdom. Princess Vivi says goodbye to her friends, choosing duty over adventure - but the mark on their arms, hidden from the Marines, proves they'll always be nakama. As the Going Merry sails toward the next adventure, Luffy stands on the figurehead, laughing at the horizon. The King of Pirates isn't a title. It's a promise. And he always keeps his promises.`,
      speaker: null,
      choices: [
        {
          id: "celebrate",
          label: "Celebrate your victory!",
          outcomes: {
            success: {
              text: `--- THE END ---`,
              speaker: "Narrator",
            },
          },
        },
      ],
    },

    epilogue_defeat: {
      id: "epilogue_defeat",
      title: "Defeat",
      type: "narrative",
      isEnding: true,
      background: "https://rosebud.ai/assets/defeat.jpg?cKYF",
      music: "https://rosebud.ai/assets/epilogue.mp3?kXtF",
      openingText: `The desert claims everything. Crocodile's sand buries hope, buries dreams, buries the crew's conviction that friendship conquers all. Scattered across Alabasta, defeated and alone, each Straw Hat faces their darkest moment. But even in defeat, even in despair, a rubber hand reaches out from the sand. 'Not... done... yet...!' Because Straw Hats don't give up. They get up. They always get up.`,
      speaker: null,
      choices: [
        {
          id: "accept_fate",
          label: "Accept your fate...",
          outcomes: {
            success: {
              text: `--- THE END ---`,
              speaker: "Narrator",
            },
          },
        },
      ],
    },
  },
};