// ═══════════════════════════════════════════════════════════════════════════════
// MANIFEST.JS - Wednesday: Shadows of Nevermore
// ═══════════════════════════════════════════════════════════════════════════════
// Auto-generated by create_game.py
// ═══════════════════════════════════════════════════════════════════════════════

export const manifest = {

  // ─────────────────────────────────────────────────────────────────────────────
  // GAME METADATA
  // ─────────────────────────────────────────────────────────────────────────────
  id: "wednesday",
  title: "Wednesday: Shadows of Nevermore",
  description: "A dark mystery adventure where Wednesday Addams and her unlikely allies must uncover the sinister secrets lurking within Nevermore Academy before an ancient evil awakens.",
  theme: "wednesday",
  startingScene: "intro",
  defeatScene: "epilogue_defeat",

  // ─────────────────────────────────────────────────────────────────────────────
  // UI THEME
  // ─────────────────────────────────────────────────────────────────────────────
  ui: {
    fonts: {
      primary: "'Crimson Text', Georgia, 'Times New Roman', serif",
      monospace: "'Courier New', Courier, monospace",
      heading: "'Cinzel', Georgia, 'Times New Roman', serif",
      sizes: {
        title: "17px",
        heading: "15px",
        body: "14px",
        small: "13px",
        tiny: "12px",
      },
      metrics: {
        lineHeight: 1.4,
        buttonPadding: 1.5,
        sectionGap: 2.0,
        charWidth: 0.55,
        descenderPadding: {
          small: { top: 2, bottom: 6 },
          medium: { top: 3, bottom: 8 },
          large: { top: 4, bottom: 10 },
        },
      },
    },
    colors: {
      dialogBg: 0x1a0a1a,
      dialogBorder: 0x6b2d6b,
      panelBg: 0x0d050d,
      textPrimary: '#9b4d9b',
      textSecondary: '#4a1a4a',
      textSpeaker: '#c77dc7',
      textDisabled: '#666666',
      buttonNormal: 0x2d2d44,
      buttonHover: 0x4a4a6a,
      buttonDisabled: 0x222233,
      buttonText: '#ffffff',
      healthOk: 0x4ade80,
      healthHurt: 0xfbbf24,
      healthCritical: 0xff6b6b,
      healthDown: 0xef4444,
      healthBarBg: 0x333333,
      initiative: {
        currentEnemy: 0x8b0000,
        currentParty: 0x2d5a27,
        inactive: 0x1a1a2e,
        enemyName: '#ff6666',
        partyName: '#88ff88',
        currentName: '#ffffff',
        indicator: '#ffff00',
      },
      enemy: {
        name: '#ff6b6b',
        placeholder: 0xcc0000,
      },
      party: {
        placeholder: 0x00cc00,
      },
      actionButton: {
        bg: 0x2d5a27,
        bgHover: 0x3d7a37,
        border: 0x4ade80,
        borderHover: 0x6bef6b,
      },
      infoButton: {
        bg: 0x3a3a5a,
        bgHover: 0x5a5a7a,
      },
      combat: {
        damageFlash: 0xff0000,
        damageText: '#ff4444',
        healText: '#44ff44',
        textStroke: '#000000',
      },
      dice: {
        critical: 0xffd700,
        success: 0x4ade80,
        partial: 0xfbbf24,
        failure: 0xef4444,
        boxBg: 0x333355,
        boxBorder: 0x666688,
        criticalTint: 0x4a6741,
        failureTint: 0x6b3030,
      },
      overlay: {
        dark: 0x000000,
        gradient1: 0x16213e,
        gradient2: 0x0f3460,
        victoryFlash: 0xffd700,
        defeatTint: 0x8b0000,
      },
      backButton: {
        bg: 0x2a2a3a,
        bgHover: 0x3a3a4a,
      },
    },
    dimensions: {
      healthBar: { width: 50, height: 10, borderRadius: 3 },
      enemyHealthBar: { width: 100, height: 12, borderRadius: 4, yOffset: 20 },
      portrait: { small: 20, medium: 22, large: 40 },
      initiative: { entryHeight: 30, panelWidth: 170, padding: 5 },
      ability: { buttonHeight: 52, buttonSpacing: 8, borderRadius: 6, namePaddingTop: 8, descPaddingTop: 28, rightColumnX: 45, sectionSpacing: 16 },
      dialogue: { padding: 20, speakerY: 15, textY: 45, indicatorSize: 14, borderRadius: 12 },
    },
    spacing: { healthBarRow: 28, portraitOffset: 15, nameOffset: 40 },
    animation: { damageFlash: 80, highlightPulse: 400, continuePulse: 600, healGlow: 150 },
    labels: {
      characterSelect: "Choose an Outcast:",
      unknownCharacter: "A mysterious figure",
      abilitySelect: "Select Action:",
      basicAttacksSection: "-- Standard Actions --",
      specialAbilitiesSection: "-- Special Abilities --",
      initiativeHeader: "TURN ORDER",
      initiativeTitle: "TURN ORDER",
      roundTransition: "--- ROUND {round} ---",
      narrator: "Narrator",
      defeated: "FALLEN",
      hpLabel: "HP",
      continueIndicator: "▼",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // AI/NARRATOR CONFIGURATION
  // ─────────────────────────────────────────────────────────────────────────────
  ai: {
    projectId: "wednesday",
    partyTerms: {
      singular: "Outcast",
      plural: "Outcasts",
      adjective: "Outcast-forged",
      description: "a member of the party",
    },
    fallbackNarration: {
      breakFreeSuccess: "breaks free from the restraints",
      breakFreeFailure: "struggles against the restraints but remains trapped",
      unconscious: "is unconscious and cannot act",
      effects: {
        restrain: "The target is restrained!",
        poison: "Corruption deals {damage} additional damage!",
        slow: "The target is slowed!",
        mark: "The target is marked for bonus damage!",
        shield: "A protective barrier is raised!",
        concealment: "The party fades into concealment!",
        damage_reduction: "Defenses are weakened!",
        default: "{type} effect applied!",
      },
    },
    narratorPrompt: `You are the narrator for "Wednesday: Shadows of Nevermore", A dark mystery adventure where Wednesday Addams and her unlikely allies must uncover the sinister se...

Your tone is:
- Dry, sardonic wit delivered with the enthusiasm of someone reading their own obituary - deadpan and darkly humorous

Rules:
- Keep responses under 3 sentences unless asked for more
- Never break character or mention being an AI
- Make everything sound dramatic and entertaining
- Use short, punchy sentences`,
    narratorTone: {
      style: ["Dry, sardonic wit delivered with the enthusiasm of someone reading their own obituary - deadpan and darkly humorous", "Gothic atmosphere dripping from every description - emphasize shadows, fog, creeping dread, and the occasional dramatic raven", "Treats the macabre as mundane and the mundane as suspicious - death is fascinating, cheerfulness is deeply concerning"],
      rules: [
        "Keep responses to 2-3 sentences MAX",
        "Never break character or mention being an AI",
        "Make everything sound more epic than it probably is"
      ]
    },
    personalityStyles: {
      reckless: "impulsive, enthusiastic, charges in without thinking",
      paranoid: "suspicious, scheming, always has a backup plan",
      cheerful: "optimistic, accidentally competent, finds joy in chaos",
      sardonic: "sarcastic, weary, secretly caring",
    },
    narrationInstructions: {
      healParty: "channeling healing energy that flows to ALL party members!",
      buffParty: "CASTING protective magic over the ENTIRE party!",
      healSelf: "healing themselves with a burst of energy!",
    },
    npcPrompts: {}
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SCENE DISPLAY CONFIGURATION
  // ─────────────────────────────────────────────────────────────────────────────
  sceneDisplay: {
    victoryScenes: ["midboss_victory", "epilogue_victory"],
    dynamicCharacterDefaults: {
      x: 0.5,
      y: 0.45,
      maxSize: 180,
      successAnimation: { type: "bounce", duration: 600, ease: "Back.easeOut" },
      failureAnimation: { type: "shake", duration: 400, ease: "Power2" }
    },
    scenes: {
      midboss_victory: {
        party: { show: true, pose: "idle", y: 0.45, spacing: 0.2, startX: 0.15, maxSize: 140 }
      },
      epilogue_victory: {
        party: { show: true, pose: "idle", y: 0.45, spacing: 0.2, startX: 0.15, maxSize: 140 }
      }
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PARTY MEMBERS
  // ─────────────────────────────────────────────────────────────────────────────
  party: [
    {
      id: "wednesday_addams",
      name: "Wednesday Addams",
      images: {
        idle: "https://rosebud.ai/assets/wednesday_addams-idle.png?Bzem",
        attack: "https://rosebud.ai/assets/wednesday_addams-attack.png?0U56",
        hurt: "https://rosebud.ai/assets/wednesday_addams-hurt.png?2JFR",
        portrait: "https://rosebud.ai/assets/wednesday_addams-portrait.png?pzGV",
      },
      gender: "female",
      pronouns: { subject: "she", object: "her", possessive: "her" },
      class: "Enforcer",
      stats: {
        brawn: 2,
        cunning: 1,
        spirit: 0,
      },
      maxHealth: 5,
      trait: "morbid",
      description: "A deadpan teenage detective with a penchant for the macabre, wielding intimidation and morbid curiosity as her primary weapons",
      personality: "Wednesday speaks in a flat, emotionless monotone that somehow conveys more menace than any shouting. She finds joy in others' discomfort and approaches murder investigations with genuine enthusiasm.",
      song: "I don't dance. I don't smile. I plot revenge with meticulous detail. If you see me approaching, it's already too late. Your suffering will be... adequate.",
    },    {
      id: "enid_sinclair",
      name: "Enid Sinclair",
      images: {
        idle: "https://rosebud.ai/assets/enid_sinclair-idle.png?bn9y",
        attack: "https://rosebud.ai/assets/enid_sinclair-attack.png?hZGD",
        hurt: "https://rosebud.ai/assets/enid_sinclair-hurt.png?JDKg",
        portrait: "https://rosebud.ai/assets/enid_sinclair-portrait.png?hGSb",
      },
      gender: "female",
      pronouns: { subject: "she", object: "her", possessive: "her" },
      class: "Scout",
      stats: {
        brawn: 0,
        cunning: 2,
        spirit: 1,
      },
      maxHealth: 5,
      trait: "peppy",
      description: "A colorful werewolf with an infectious personality, expert at navigating social situations and gathering information through sheer friendliness",
      personality: "Enid is aggressively optimistic in the face of darkness, using her social butterfly skills and werewolf senses to help the team. She desperately wants Wednesday to like her, despite all evidence suggesting otherwise.",
      song: "OMG, we're totally going to solve this mystery! Did you know I have like, the BEST hearing? Also my claws are coming in any day now. Any. Day. Now. Positive vibes only!",
    },    {
      id: "eugene_ottinger",
      name: "Eugene Ottinger",
      images: {
        idle: "https://rosebud.ai/assets/eugene_ottinger-idle.png?vFQa",
        attack: "https://rosebud.ai/assets/eugene_ottinger-attack.png?n5f9",
        hurt: "https://rosebud.ai/assets/eugene_ottinger-hurt.png?3rTI",
        portrait: "https://rosebud.ai/assets/eugene_ottinger-portrait.png?mFj0",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Hacker",
      stats: {
        brawn: 0,
        cunning: 1,
        spirit: 2,
      },
      maxHealth: 5,
      trait: "nerdy",
      description: "President of the Hummers beekeeping club, wielding his bee swarm as both weapon and surveillance network",
      personality: "Eugene is earnest, slightly awkward, and treats his bees like a personal army of tiny friends. He's devoted to Wednesday after she showed him the slightest kindness, and his bee knowledge is surprisingly relevant to investigations.",
      song: "My bees see everything. EVERYTHING. They're not just insects, they're a network! Did you know the queen can communicate through pheromones? This is relevant, I promise!",
    },    {
      id: "thing",
      name: "Thing",
      images: {
        idle: "https://rosebud.ai/assets/thing-idle.png?HiRS",
        attack: "https://rosebud.ai/assets/thing-attack.png?zdMw",
        hurt: "https://rosebud.ai/assets/thing-hurt.png?nWix",
        portrait: "https://rosebud.ai/assets/thing-portrait.png?4E9N",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Medic",
      stats: {
        brawn: 0,
        cunning: 1,
        spirit: 2,
      },
      maxHealth: 5,
      trait: "resourceful",
      description: "A disembodied hand with centuries of Addams family service, providing support through sign language, lockpicking, and creative problem-solving",
      personality: "Thing communicates through expressive finger gestures and snapping. He's fiercely loyal to Wednesday, surprisingly capable in a crisis, and has the sneaking skills of a trained spy packed into five fingers.",
      song: "*snaps fingers rhythmically* *gestures emphatically* *points accusingly* *gives two thumbs up* *crawls away mysteriously*",
    },    {
      id: "gomez_addams",
      name: "Gomez Addams",
      images: {
        idle: "https://rosebud.ai/assets/gomez_addams-idle.webp?dmrY",
        attack: "https://rosebud.ai/assets/gomez_addams-attack.webp?dWoU",
        hurt: "https://rosebud.ai/assets/gomez_addams-hurt.webp?PvZk",
        portrait: "https://rosebud.ai/assets/gomez_addams-portrait.webp?ojUd",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Duelist",
      stats: {
        brawn: 2,
        cunning: 2,
        spirit: 1,
      },
      maxHealth: 6,
      trait: "passionate",
      description: "The patriarch of the Addams family, a master fencer and lover of all things dangerous and romantic.",
      personality: "Gomez is exuberant, intensely passionate about his wife Morticia, and finds pure joy in the macabre and the thrill of a good duel. He's fiercely protective of his daughter Wednesday, though he often expresses it through swordplay and eccentric advice.",
      song: "En garde! Life is a magnificent tragedy, and death is merely the final curtain call! Cara Mia, the moon is full, the bats are singing, and I feel... dangerously alive!",
    },    {
      id: "morticia_addams",
      name: "Morticia Addams",
      images: {
        idle: "https://rosebud.ai/assets/morticia_addams-idle.webp?2GmK",
        attack: "https://rosebud.ai/assets/morticia_addams-attack.webp?aVgk",
        hurt: "https://rosebud.ai/assets/morticia_addams-hurt.webp?s34b",
        portrait: "https://rosebud.ai/assets/morticia_addams-portrait.webp?lBFR",
      },
      gender: "female",
      pronouns: { subject: "she", object: "her", possessive: "her" },
      class: "Matriarch",
      stats: {
        brawn: 0,
        cunning: 1,
        spirit: 3,
      },
      maxHealth: 5,
      trait: "serene",
      description: "The heart of the Addams family, an elegant woman who finds beauty in the dark and strength in composure.",
      personality: "Morticia is the calm center of the Addams family whirlwind. She speaks with elegant precision, moves with feline grace, and possesses a deep, almost supernatural connection to the darker forces of nature, which she uses to nurture her family.",
      song: "Black is such a happy color, don't you think? My darling Gomez, the shadows are lengthening, and the graveyard is in full bloom. Let us celebrate the exquisite melancholy of existence.",
    },    {
      id: "lurch",
      name: "Lurch",
      images: {
        idle: "https://rosebud.ai/assets/lurch-idle.webp?mfnY",
        attack: "https://rosebud.ai/assets/lurch-attack-v2.webp?0UIt",
        hurt: "https://rosebud.ai/assets/lurch-hurt-v2.webp?euSR",
        portrait: "https://rosebud.ai/assets/lurch-portrait.webp?GoGh",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Tank",
      stats: {
        brawn: 3,
        cunning: 0,
        spirit: 1,
      },
      maxHealth: 8,
      trait: "stoic",
      description: "The faithful, towering butler of the Addams family, possessing immense strength and an unflappable nature.",
      personality: "Lurch rarely speaks, communicating instead through deep, resonant groans. He is incredibly strong, fiercely loyal, and moves with a slow, deliberate pace that belies his overwhelming power. He takes hits for the family without a second thought.",
      song: "Uuuuuuuugh. *groans deeply* You rang? The door is open, the bags are heavy, and I am... prepared. For everything. Including you.",
    },    {
      id: "uncle_fester",
      name: "Uncle Fester",
      images: {
        idle: "https://rosebud.ai/assets/uncle_fester-idle.webp?XexB",
        attack: "https://rosebud.ai/assets/uncle_fester-attack.webp?pp1Y",
        hurt: "https://rosebud.ai/assets/uncle_fester-hurt.webp?lhNm",
        portrait: "https://rosebud.ai/assets/uncle_fester-portrait.webp?KBuQ",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Elementalist",
      stats: {
        brawn: 1,
        cunning: 1,
        spirit: 3,
      },
      maxHealth: 5,
      trait: "eccentric",
      description: "Wednesday's favorite uncle, an eccentric man with a literal spark in his personality and a talent for electrical mayhem.",
      personality: "Fester is gleefully strange, possessing a high tolerance for pain and a literal ability to generate electricity. He finds the macabre delightful and is always ready with a shocking surprise or a helpful explosion. He cares deeply for Wednesday, in his own bizarre way.",
      song: "Is it hot in here, or is it just me? *illuminates lightbulb in mouth* There's nothing like a thousand volts to start the day! Don't worry, the smell of ozone is perfectly normal.",
    },    {
      id: "pugsley_addams",
      name: "Pugsley Addams",
      images: {
        idle: "https://rosebud.ai/assets/pugsley_addams-idle.webp?62HD",
        attack: "https://rosebud.ai/assets/pugsley_addams-attack-v2.webp?ddhK",
        hurt: "https://rosebud.ai/assets/pugsley_addams-hurt-v2.webp?2zA5",
        portrait: "https://rosebud.ai/assets/pugsley_addams-portrait.webp?JoNs",
      },
      gender: "male",
      pronouns: { subject: "he", object: "him", possessive: "his" },
      class: "Demolitionist",
      stats: {
        brawn: 1,
        cunning: 2,
        spirit: 2,
      },
      maxHealth: 5,
      trait: "chaotic",
      description: "Wednesday's younger brother, a budding scientist with a passion for high explosives and creative engineering.",
      personality: "Pugsley is a whirlwind of chaotic energy, always tinkering with something that probably shouldn't be tinkered with. He views every problem as an opportunity for a controlled (or uncontrolled) explosion and finds his sister's stoicism endlessly fascinating to test.",
      song: "Tick... tick... tick... BOOM! Hahaha! Did you see that? I think I can make the next one even bigger. Wednesday says I'm a public nuisance, but I prefer 'experimental physicist'.",
    }
  ],

  // ─────────────────────────────────────────────────────────────────────────────
  // ABILITIES
  // ─────────────────────────────────────────────────────────────────────────────
  abilities: {
    wednesday_addams: {
      basicAttacks: [
        {
          id: "calculated_strike",
          name: "Calculated Strike",
          description: "A precise attack aimed at maximum discomfort.",
          stat: "brawn",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "death_stare",
          name: "Death Stare",
          description: "Fix your target with a gaze that promises suffering. Slows their next move.",
          stat: "brawn",
          difficulty: "normal",
          effect: {
            type: "slow", duration: 2, description: "Frozen by Wednesday's unblinking stare"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "pointed_accusation",
          name: "Pointed Accusation",
          description: "Level a precise accusation that exposes a target's vulnerability.",
          stat: "cunning",
          difficulty: "normal",
          effect: {
            type: "mark", duration: 2, description: "Marked by Wednesday's sharp observation"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "grim_resolve",
          name: "Grim Resolve",
          description: "Internalize your dark determination, creating a mental shield against harm.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "shield", reduction: 1, duration: 2, description: "Steeled by morbid determination"
          },
          uses: 2,
          targetType: "self",
        },
        {
          id: "grim_vision",
          name: "Grim Vision",
          description: "Tap into psychic premonitions to witness the enemy's inevitable doom, exposing their vital weaknesses.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "vulnerable", amount: 1, duration: 3, description: "Doomed by a psychic vision of their own end"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "deadly_cello",
          name: "Deadly Cello",
          description: "Unleash a haunting, dissonant concerto that paralyzes all enemies in dread while invigorating the party's dark resolve.",
          stat: "spirit",
          difficulty: "hard",
          effects: [
            { 
              targetType: "enemy_all", 
              type: "stun", 
              duration: 1, 
              description: "Paralyzed by a haunting cello melody" 
            },
            { 
              targetType: "party", 
              type: "haste", 
              bonus: 2, 
              duration: 2, 
              description: "Invigorated by the dark symphony" 
            }
          ],
          uses: 1,
          targetType: "all",
        }
      ],
    },
    enid_sinclair: {
      basicAttacks: [
        {
          id: "claw_swipe",
          name: "Claw Swipe",
          description: "Attack with werewolf claws. Finally, they work!",
          stat: "cunning",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "wolf_out",
          name: "Wolf Out",
          description: "Full werewolf transformation for devastating attacks!",
          stat: "cunning",
          difficulty: "normal",
          damage: 4,
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "rainbow_rally",
          name: "Rainbow Rally",
          description: "Aggressive optimism that heals and inspires the entire party!",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "heal", amount: 2
          },
          uses: 2,
          targetType: "party",
        },
        {
          id: "claws_of_rage",
          name: "Claws of Fury",
          description: "A rapid succession of slashes that shreds enemy defenses.",
          stat: "cunning",
          difficulty: "normal",
          damage: 3,
          effect: {
            type: "mark", duration: 2, description: "Defenses shredded by Lupine rage"
          },
          uses: 2,
          targetType: "enemy",
        }
      ],
    },
    eugene_ottinger: {
      basicAttacks: [
        {
          id: "bee_assault",
          name: "Bee Assault",
          description: "Command the hive to swarm and sting enemies.",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "swarm_fury",
          name: "Swarm Fury",
          description: "Unleash the entire hive in a devastating attack!",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          effect: {
            type: "poison", damage: 1, duration: 2, description: "Venom courses through their system"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "protective_swarm",
          name: "Protective Swarm",
          description: "Form a defensive barrier of loyal bees around allies.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "shield", reduction: 1, duration: 2, description: "Protected by a living shield of bees"
          },
          uses: 2,
          targetType: "party",
        },
        {
          id: "bee_surveillance",
          name: "Bee Surveillance",
          description: "Send out a drone bee to track enemy movements, providing tactical data that boosts party accuracy.",
          stat: "cunning",
          difficulty: "normal",
          effect: {
            type: "accuracy_boost", bonus: 2, duration: 3, description: "Tactical data from surveillance bees"
          },
          uses: 2,
          targetType: "party",
        }
      ],
    },
    thing: {
      basicAttacks: [
        {
          id: "finger_flick",
          name: "Finger Flick",
          description: "A surprisingly powerful flick to vulnerable spots.",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "emergency_first_aid",
          name: "Emergency First Aid",
          description: "Apply bandages and pressure with expert dexterity.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "heal", amount: 3
          },
          uses: 2,
          targetType: "ally",
        },
        {
          id: "distraction_snap",
          name: "Distraction Snap",
          description: "Snap fingers to create a diversion, drawing enemy attention.",
          stat: "cunning",
          difficulty: "normal",
          effect: {
            type: "taunt", duration: 1, description: "Utterly distracted by the snapping hand"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "handy_assistance",
          name: "Handy Assistance",
          description: "Thing provides a literal extra hand, boosting an ally's utility and speed for their next actions.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "haste", bonus: 2, duration: 2, description: "Assisted by Thing's nimble fingers"
          },
          uses: 2,
          targetType: "ally",
        },
        {
          id: "lockpick_precision",
          name: "Lockpick Precision",
          description: "Identify structural weaknesses with professional skill, marking the target.",
          stat: "cunning",
          difficulty: "normal",
          effect: {
            type: "mark", duration: 2, description: "Vulnerabilities exposed by Thing's precision"
          },
          uses: 2,
          targetType: "enemy",
        }
      ],
    },
    gomez_addams: {
      basicAttacks: [
        {
          id: "rapier_thrust",
          name: "Rapier Thrust",
          description: "A sharp, elegant lunge with a fencing rapier.",
          stat: "cunning",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "fencing_flurry",
          name: "Fencing Flurry",
          description: "Execute a rapid succession of low-damage strikes that overwhelm the target.",
          stat: "cunning",
          difficulty: "normal",
          damage: 1,
          multiHit: 4,
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "mon_amour",
          name: "Mon Amour",
          description: "Gomez channels his intense passion to inspire an ally, shielding them.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "shield", reduction: 2, duration: 2, description: "Protected by Gomez's exuberant passion"
          },
          uses: 2,
          targetType: "ally",
        },
        {
          id: "exuberant_charge",
          name: "Exuberant Charge",
          description: "Charge headlong into danger with infectious enthusiasm, boosting party accuracy.",
          stat: "brawn",
          difficulty: "normal",
          damage: 2,
          effect: {
            type: "accuracy_boost", bonus: 2, duration: 2, description: "Inspired by Gomez's reckless bravery"
          },
          uses: 2,
          targetType: "enemy",
        }
      ],
    },
    morticia_addams: {
      basicAttacks: [
        {
          id: "elegant_slap",
          name: "Elegant Slap",
          description: "A composed yet stinging reprimand.",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "willow_weep",
          name: "Willow Weep",
          description: "Morticia channels her connection to the weeping willow, soothing and healing the entire party.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "heal", amount: 2
          },
          uses: 2,
          targetType: "party",
        },
        {
          id: "thorned_embrace",
          name: "Thorned Embrace",
          description: "Call upon the protective thorns of her garden to shield an ally.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "shield", reduction: 2, duration: 3, description: "Protected by spectral thorns"
          },
          uses: 2,
          targetType: "ally",
        },
        {
          id: "nightshade_kiss",
          name: "Nightshade Kiss",
          description: "A dark blessing that weakens an enemy's resolve.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "vulnerable", amount: 1, duration: 2, description: "Weakened by Morticia's dark blessing"
          },
          uses: 2,
          targetType: "enemy",
        }
      ],
    },
    lurch: {
      basicAttacks: [
        {
          id: "heavy_hand",
          name: "Heavy Hand",
          description: "A slow but incredibly powerful blow.",
          stat: "brawn",
          difficulty: "normal",
          damage: 3,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "shove",
          name: "Shove",
          description: "Use your massive frame to knock back the enemy, dazing them.",
          stat: "brawn",
          difficulty: "normal",
          damage: 2,
          effect: {
            type: "stun", duration: 1, description: "Stunned by Lurch's massive shove"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "towering_presence",
          name: "Towering Presence",
          description: "Draw all enemy attention to yourself with your intimidating height.",
          stat: "brawn",
          difficulty: "normal",
          effect: {
            type: "taunt", duration: 2, description: "Fixated on the towering butler"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "immovable_object",
          name: "Immovable Object",
          description: "Brace for impact, further increasing your already formidable defenses.",
          stat: "brawn",
          difficulty: "normal",
          effect: {
            type: "shield", reduction: 2, duration: 2, description: "Braced for impact"
          },
          uses: 2,
          targetType: "self",
        }
      ],
    },
    uncle_fester: {
      basicAttacks: [
        {
          id: "electric_touch",
          name: "Electric Touch",
          description: "A shocking touch that delivers a direct current of mayhem.",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "static_shield",
          name: "Static Shield",
          description: "Generate a field of crackling electricity that shocks anyone who dares to strike you.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "static_shield", duration: 3, description: "Protected by a crackling electrical field"
          },
          uses: 2,
          targetType: "self",
        },
        {
          id: "conductive_bolt",
          name: "Conductive Bolt",
          description: "Unleash a powerful bolt of electricity that chains between all enemies.",
          stat: "spirit",
          difficulty: "normal",
          damage: 2,
          uses: 2,
          targetType: "area",
        },
        {
          id: "explosive_departure",
          name: "Explosive Departure",
          description: "A sudden, booming explosion that dazes and weakens enemies.",
          stat: "spirit",
          difficulty: "normal",
          damage: 1,
          effect: {
            type: "stun", duration: 1, description: "Dazed by a sudden blast"
          },
          uses: 2,
          targetType: "enemy",
        }
      ],
    },
    pugsley_addams: {
      basicAttacks: [
        {
          id: "tinker_wrench",
          name: "Tinker Wrench",
          description: "A solid thwack with a heavy mechanical tool.",
          stat: "brawn",
          difficulty: "normal",
          damage: 2,
          targetType: "enemy",
        }
      ],
      specialAbilities: [
        {
          id: "playful_pyromania",
          name: "Playful Pyromania",
          description: "Toss a homemade grenade that deals damage and leaves a burning damage-over-time effect.",
          stat: "cunning",
          difficulty: "normal",
          damage: 2,
          effect: {
            type: "poison", damage: 1, duration: 3, description: "Engulfed in playful flames"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "guillotine_test",
          name: "Guillotine Test",
          description: "A precisely timed mechanism that marks an enemy for extra damage.",
          stat: "cunning",
          difficulty: "normal",
          damage: 2,
          effect: {
            type: "mark", duration: 2, description: "Pinned by a test mechanism"
          },
          uses: 2,
          targetType: "enemy",
        },
        {
          id: "experimental_shield",
          name: "Experimental Shield",
          description: "Deploy a prototype energy shield that might... just might work.",
          stat: "spirit",
          difficulty: "normal",
          effect: {
            type: "shield", reduction: 2, duration: 2, description: "Protected by an experimental field"
          },
          uses: 2,
          targetType: "party",
        }
      ],
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // ENEMIES
  // ─────────────────────────────────────────────────────────────────────────────
  enemies: {
    laurel_gates: {
      id: "laurel_gates",
      name: "Laurel Gates",
      shortName: "Laurel",
      images: {
        idle: "https://rosebud.ai/assets/laurel_gates-idle.png?awKU",
        attack: "https://rosebud.ai/assets/laurel_gates-attack.png?wjRr",
        hurt: "https://rosebud.ai/assets/laurel_gates-hurt.png?lTGF",
        dead: "https://rosebud.ai/assets/laurel_gates-dead.png?eLLa",
        portrait: "https://rosebud.ai/assets/laurel_gates-portrait.png?mdN8",
        special: "https://rosebud.ai/assets/laurel_gates-special.png?nA8h",
      },
      creatureType: "Human",
      size: "Medium",
      description: "A descendant of Joseph Crackstone's loyal followers, hiding centuries of hatred behind a mask of kindness as the school's guidance counselor",
      personality: "Laurel is masterfully manipulative, using her position and seemingly caring demeanor to orchestrate events from the shadows. Her pleasant exterior conceals fanatical devotion to her ancestor's genocidal mission.",
      health: 12,
      stats: {
        cunning: 2,
      },
      attacks: [
        {
          id: "poisoned_words",
          name: "Poisoned Words",
          description: "Uses psychological manipulation to turn allies against each other",
          damage: 1,
          damageType: "psychic",
          targeting: "highest_threat",
        },
        {
          id: "nightshade_dart",
          name: "Nightshade Dart",
          description: "Fires a poison-tipped dart from a hidden weapon",
          damage: 2,
          damageType: "poison",
          targeting: "lowest_health",
        }
      ],
    },
    the_hyde: {
      id: "the_hyde",
      name: "The Hyde",
      shortName: "The Hyde",
      images: {
        idle: "https://rosebud.ai/assets/the_hyde-idle.png?eVv7",
        attack: "https://rosebud.ai/assets/the_hyde-attack.png?NAT3",
        hurt: "https://rosebud.ai/assets/the_hyde-hurt.png?ObEh",
        dead: "https://rosebud.ai/assets/the_hyde-dead.png?m4kJ",
        portrait: "https://rosebud.ai/assets/the_hyde-portrait.png?QHN8",
        attack2: "https://rosebud.ai/assets/the_hyde-attack2.png?X8N3",
        special1: "https://rosebud.ai/assets/the_hyde-special1.png?gdG2",
        special2: "https://rosebud.ai/assets/the_hyde-special2.png?9V4G",
        transform: "https://rosebud.ai/assets/the_hyde-transform.png?PLbH",
      },
      creatureType: "Monster",
      size: "Large",
      description: "Tyler Galpin's monstrous alter ego - a pale, muscular abomination with razor claws and dead eyes, completely under the control of his 'master'",
      personality: "The Hyde is a vessel of rage and destruction, stripped of Tyler's humanity. It operates on pure predatory instinct, showing no mercy and feeling no pain, a perfect weapon aimed at outcasts.",
      health: 18,
      stats: {
        cunning: 1,
      },
      attacks: [
        {
          id: "savage_claws",
          name: "Savage Claws",
          description: "Rakes targets with razor-sharp claws capable of tearing through stone",
          damage: 3,
          damageType: "slashing",
          targeting: "highest_threat",
        },
        {
          id: "berserker_charge",
          name: "Berserker Charge",
          description: "Charges through obstacles to slam into prey",
          damage: 2,
          damageType: "physical",
          targeting: "grouped",
        },
        {
          id: "primal_howl",
          name: "Primal Howl",
          description: "Unleashes a terrifying howl that freezes prey in fear",
          damage: 1,
          damageType: "psychic",
          targeting: "all_enemies",
        }
      ],
    }
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SCENES
  // ─────────────────────────────────────────────────────────────────────────────
  scenes: {
    intro: {
      id: "intro",
      title: "Wednesday: Shadows of Nevermore",
      type: "narrative",
      background: "https://rosebud.ai/assets/nevermore_gates.jpg?MNmS",
      music: "https://rosebud.ai/assets/Witchcraftloop_-_fantasy_-_guitar_-_piano.mp3?GZPi",
      openingText: `You are OUTCASTS. Within the gothic halls of Nevermore Academy, where werewolves attend classes and sirens sing in the showers, you exist on the fringes even among freaks. Now, murders plague Jericho, an ancient evil stirs beneath the school, and somehow, solving this mystery has fallen to a deadpan Addams, a peppy werewolf, a bee enthusiast, and a disembodied hand. How reassuring.`,
      speaker: null,
      nextScene: "mission_briefing",
    },

    mission_briefing: {
      id: "mission_briefing",
      title: "The Mission",
      type: "narrative",
      background: "https://rosebud.ai/assets/quad_courtyard.jpg?qhWV",
      music: "https://rosebud.ai/assets/Forestguitar_-_piano_-_anxiety_-_mysterious.mp3?aNfW",
      openingText: `Bodies are appearing across Jericho, torn apart by something inhuman. The normies blame Nevermore. Principal Weems demands discretion. But Wednesday Addams doesn't do discretion - she does investigation, intimidation, and if necessary, retaliation. The hunt for the monster begins tonight.`,
      speaker: "The Glitch",
      choices: [
        {
          id: "accept_enthusiastically",
          label: "Accept enthusiastically!",
          character: "wednesday_addams",
          stat: "brawn",
          difficulty: "normal",
          outcomes: {
            success: {
              text: "Your enthusiasm is noted. The mission is on!",
              nextScene: "challenge_scene",
            },
            failure: {
              text: "Your enthusiasm is... excessive. But the mission continues.",
              nextScene: "challenge_scene",
            },
          },
        },
        {
          id: "plan_carefully",
          label: "Demand more details first",
          character: "enid_sinclair",
          stat: "cunning",
          difficulty: "normal",
          outcomes: {
            success: {
              text: "Smart thinking. You gather additional intel before proceeding.",
              setFlag: "got_intel",
              nextScene: "challenge_scene",
            },
            failure: {
              text: "The broker doesn't appreciate the questions. Moving on...",
              nextScene: "challenge_scene",
            },
          },
        },
      ],
    },

    challenge_scene: {
      id: "challenge_scene",
      title: "The Checkpoint",
      type: "narrative",
      background: "https://rosebud.ai/assets/wednesday_dorm.jpg?LsWy",
      music: "https://rosebud.ai/assets/Forestguitar_-_piano_-_anxiety_-_mysterious.mp3?aNfW",
      openingText: `The team must infiltrate the Jericho Sheriff's office to access case files. This requires Enid's social manipulation, Eugene's bee-based surveillance, Thing's lockpicking, and Wednesday standing menacingly in the background. Success depends on whether anyone notices the hand crawling through the vents.`,
      speaker: null,
      nextScene: "journey",
    },

    journey: {
      id: "journey",
      title: "The Journey",
      type: "narrative",
      background: "https://rosebud.ai/assets/weathervane_cafe.jpg?Sk4H",
      music: "https://rosebud.ai/assets/Forestguitar_-_piano_-_anxiety_-_mysterious.mp3?aNfW",
      openingText: `Following the clues leads the party through Jericho's darker corners: the pilgrim cemetery where gravestones whisper secrets, the abandoned mill where screams echo at night, and the town archives holding truths the founders tried to bury. Each step reveals more of the conspiracy.`,
      speaker: null,
      nextScene: "midboss_combat",
    },

    midboss_combat: {
      id: "midboss_combat",
      title: "Confrontation",
      type: "combat",
      background: "https://rosebud.ai/assets/pilgrim_cemetery.jpg?BO62",
      music: "https://rosebud.ai/assets/Forgotten_Wordsloop_-_guitar_-_magnificent_-_ancient.mp3?rQyC",
      combat: {
        version: 2,
        enemyId: "laurel_gates",
        openingNarration: `Laurel Gates drops her mask of kindness, revealing centuries of hatred inherited from her pilgrim ancestors. She's been manipulating events all along, and now she'll eliminate these meddling outcasts personally. Her poisoned words and poisoned darts are equally deadly.`,
        victoryScene: "midboss_victory",
        defeatScene: "epilogue_defeat",
      },
    },

    midboss_victory: {
      id: "midboss_victory",
      title: "Victory!",
      type: "narrative",
      background: "https://rosebud.ai/assets/nevermore_library.jpg?H9p3",
      music: "https://rosebud.ai/assets/death_and_honor.mp3?pCFz",
      openingText: `Laurel retreats, her plans disrupted but not destroyed. She's already awakened something far worse - the Hyde, and soon, Crackstone himself. The team has won this battle, but Wednesday's expression suggests she knows the real fight is just beginning.`,
      speaker: null,
      nextScene: "obstacle",
    },

    obstacle: {
      id: "obstacle",
      title: "The Void",
      type: "narrative",
      background: "https://rosebud.ai/assets/crackstone_crypt.jpg?ya4e",
      music: "https://rosebud.ai/assets/Forestguitar_-_piano_-_anxiety_-_mysterious.mp3?aNfW",
      openingText: `To reach Crackstone's crypt before the ritual completes, the team must navigate Nevermore's hidden passages - ancient tunnels filled with traps left by the founders, spectral guardians, and the bones of outcasts who came before. The walls themselves seem to watch and judge.`,
      speaker: null,
      nextScene: "explore_lair",
    },

    explore_lair: {
      id: "explore_lair",
      title: "The Lair",
      type: "narrative",
      background: "https://rosebud.ai/assets/laurel_office.jpg?hY4a",
      music: "https://rosebud.ai/assets/Forestguitar_-_piano_-_anxiety_-_mysterious.mp3?aNfW",
      openingText: `The crypt is a nightmare of pilgrim fanaticism - torture devices, occult symbols, and at its heart, Crackstone's sarcophagus beginning to crack. Laurel's final preparations are evident everywhere. The team must act before the resurrection completes.`,
      speaker: null,
      nextScene: "finalboss_combat",
    },

    finalboss_combat: {
      id: "finalboss_combat",
      title: "Final Battle",
      type: "combat",
      background: "https://rosebud.ai/assets/hyde_cave.jpg?9lZ8",
      music: "https://rosebud.ai/assets/Ritualloop_-_dark_-_drone.mp3?jeYz",
      combat: {
        version: 2,
        enemyId: "the_hyde",
        openingNarration: `The Hyde crashes through the crypt wall, Tyler Galpin's humanity completely gone. Behind the monster, Crackstone's spirit rises from his tomb, spectral flames dancing around his pilgrim robes. Two nightmares, one purpose: the extermination of all outcasts, starting with these four.`,
        victoryScene: "epilogue_victory",
        defeatScene: "epilogue_defeat",
      },
    },

    epilogue_victory: {
      id: "epilogue_victory",
      title: "Victory!",
      type: "narrative",
      isEnding: true,
      background: "https://rosebud.ai/assets/victory.jpg?qNw3",
      music: "https://rosebud.ai/assets/death_and_honor.mp3?pCFz",
      openingText: `The Hyde falls, and with Crackstone's spirit banished back to whatever hell spawned it, dawn breaks over Nevermore. Wednesday stands over Tyler's unconscious form, no satisfaction in her eyes - only the next mystery already forming. Enid hugs everyone whether they want it or not. Eugene's bees survived. Thing gives a thumbs up. Nevermore endures, as it always has.`,
      speaker: null,
      choices: [
        {
          id: "celebrate",
          label: "Celebrate your victory!",
          outcomes: {
            success: {
              text: `--- THE END ---`,
              speaker: "Narrator",
            },
          },
        },
      ],
    },

    epilogue_defeat: {
      id: "epilogue_defeat",
      title: "Defeat",
      type: "narrative",
      isEnding: true,
      background: "https://rosebud.ai/assets/defeat.jpg?FCS7",
      music: "https://rosebud.ai/assets/03_-_ekko.mp3?xNLt",
      openingText: `Crackstone's flames consume everything as his crusade finally succeeds. Nevermore burns. The outcasts fall. In her final moments, Wednesday's only regret is not having time to write about it. The monster that was Tyler howls in triumph as centuries of sanctuary become ash and memory.`,
      speaker: null,
      choices: [
        {
          id: "accept_fate",
          label: "Accept your fate...",
          outcomes: {
            success: {
              text: `--- THE END ---`,
              speaker: "Narrator",
            },
          },
        },
      ],
    },
  },
};
